### ISSUE TITLE
I can view the homepage 

### ISSUE THREAD

**Issue by bitsandbooks** [bitsandbooks/devilvader#1]
As a non-credentialed user I can visit the homepage. 

Railscasts is good for this: https://www.youtube.com/watch?v=-2W7GpolcJ4

For this you probably just need the basic controller action with static views rather than the database-backed content.

**Comment by mcelaney** [comment]
@bitsandbooks I edited this issue because I am a jerk.

**Comment by mcelaney** [comment]
Completed example: https://github.com/mcelaney/WebLincr/tree/01-homepage

**Comment by bitsandbooks** [comment]
Issue fixed with commit 6e63bf35c203cd3d5490e9224293979e40bf156b.
